name: Elixir CI

on: push

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup elixir
      uses: actions/setup-elixir@v1
      with:
        elixir-version: 1.10.1
        otp-version: 22.2.7
    - name: Cache Build
      id: cache-build
      uses: actions/cache@v1
      with:
        path: _build
        key: ${{ runner.os }}-mix-${{ hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}-build
        restore-keys: |
          ${{ runner.os }}-mix-
    - name: Cache Test Build
      id: cache-build-test
      uses: actions/cache@v1
      with:
        path: _build
        key: ${{ runner.os }}-mix-${{ hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}-build-test
        restore-keys: |
          ${{ runner.os }}-mix-
    - name: Cache Dependencies
      id: cache-deps
      uses: actions/cache@v1
      with:
        path: deps
        key: ${{ runner.os }}-mix-${{ hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}-deps
        restore-keys: |
          ${{ runner.os }}-mix-
    - name: Install Dependencies
      if: steps.cache-deps.outputs.cache-hit != 'true'
      run: mix deps.get
    - name: Compile Dependencies
      if: steps.cache-build.outputs.cache-hit != 'true'
      run: mix deps.compile
    - name: Compile Test Dependencies
      if: steps.cache-build-test.outputs.cache-hit != 'true'
      run: mix deps.compile
      env:
        MIX_ENV: test
    - name: Compile LibJudge
      run: mix compile --force --warnings-as-errors --all-warnings

  formatting:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@v2
    - name: Setup elixir
      uses: actions/setup-elixir@v1
      with:
        elixir-version: 1.10.1
        otp-version: 22.2.7
    - name: Cache Build
      id: cache-build
      uses: actions/cache@v1
      with:
        path: _build
        key: ${{ runner.os }}-mix-${{ hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}-build
        restore-keys: |
          ${{ runner.os }}-mix-
    - name: Cache Dependencies
      id: cache-deps
      uses: actions/cache@v1
      with:
        path: deps
        key: ${{ runner.os }}-mix-${{ hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}-deps
        restore-keys: |
          ${{ runner.os }}-mix-
    - name: Check Formatting
      run: mix format --check-formatted

  credo:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@v2
    - name: Setup elixir
      uses: actions/setup-elixir@v1
      with:
        elixir-version: 1.10.1
        otp-version: 22.2.7
    - name: Cache Build
      id: cache-build
      uses: actions/cache@v1
      with:
        path: _build
        key: ${{ runner.os }}-mix-${{ hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}-build
        restore-keys: |
          ${{ runner.os }}-mix-
    - name: Cache Dependencies
      id: cache-deps
      uses: actions/cache@v1
      with:
        path: deps
        key: ${{ runner.os }}-mix-${{ hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}-deps
        restore-keys: |
          ${{ runner.os }}-mix-
    - name: Lint
      run: mix credo --strict

  dialyzer:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@v2
    - name: Setup elixir
      uses: actions/setup-elixir@v1
      with:
        elixir-version: 1.10.1
        otp-version: 22.2.7
    - name: Cache Build
      id: cache-build
      uses: actions/cache@v1
      with:
        path: _build
        key: ${{ runner.os }}-mix-${{ hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}-build
        restore-keys: |
          ${{ runner.os }}-mix-
    - name: Cache Dependencies
      id: cache-deps
      uses: actions/cache@v1
      with:
        path: deps
        key: ${{ runner.os }}-mix-${{ hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}-deps
        restore-keys: |
          ${{ runner.os }}-mix-
    - name: Cache PLTs
      id: cache-plt
      uses: actions/cache@v1
      with:
        path: _build/dev
        key: ${{ runner.os }}-mix-${{ hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}-plt
        restore-keys: |
          ${{ runner.os }}-mix-
    - name: Run Static Analysis
      run: mix dialyzer --halt-exit-status

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@v2
    - name: Setup elixir
      uses: actions/setup-elixir@v1
      with:
        elixir-version: 1.10.1
        otp-version: 22.2.7
    - name: Cache Build
      id: cache-build
      uses: actions/cache@v1
      with:
        path: _build
        key: ${{ runner.os }}-mix-${{ hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}-build-test
        restore-keys: |
          ${{ runner.os }}-mix-
    - name: Cache Dependencies
      id: cache-deps
      uses: actions/cache@v1
      with:
        path: deps
        key: ${{ runner.os }}-mix-${{ hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}-deps
        restore-keys: |
          ${{ runner.os }}-mix-
    - name: Run Tests
      run: mix test
